/**
 * Context Window Monitoring Service.
 *
 * Uses GetCascadeTrajectorySteps (with cascadeId) to retrieve REAL
 * token usage from the latest RESPONSE step. Each response step contains:
 *   - inputTokens: uncached prompt tokens sent to the model
 *   - cacheReadTokens: cached prompt tokens (still counts toward context window)
 *   - outputTokens: tokens generated by the model
 *   - model: internal model ID (e.g. MODEL_PLACEHOLDER_M26)
 *   - apiProvider: provider (e.g. API_PROVIDER_ANTHROPIC_VERTEX)
 *
 * Context window usage = inputTokens + cacheReadTokens (total prompt sent to model).
 */
import type { ContextSnapshot, ContextUpdateCallback, ServerConnection } from '../types';
import { logDebug, logInfo, logWarning } from '../logging/logger';
import type { ModelRegistry } from './model-registry';
import * as http from 'http';

const GET_TRAJECTORIES_PATH =
  '/exa.language_server_pb.LanguageServerService/GetAllCascadeTrajectories';
const GET_STEPS_PATH =
  '/exa.language_server_pb.LanguageServerService/GetCascadeTrajectorySteps';

/** Model placeholder → display name mapping (from apiProvider) */
const API_PROVIDER_LABELS: Record<string, string> = {
  API_PROVIDER_ANTHROPIC_VERTEX: 'Claude',
  API_PROVIDER_ANTHROPIC: 'Claude',
  API_PROVIDER_GOOGLE: 'Gemini',
  API_PROVIDER_GOOGLE_VERTEX: 'Gemini',
  API_PROVIDER_OPENAI: 'GPT',
};

interface TrajectorySummary {
  summary?: string;
  lastModifiedTime?: string;
  status?: string;
  stepCount?: number;
  workspaces?: Array<{ workspaceFolderAbsoluteUri?: string }>;
  [key: string]: unknown;
}

interface StepTokenInfo {
  model: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  apiProvider: string;
}

export class ContextService {
  private lastSnapshot: ContextSnapshot | null = null;
  private updateCallbacks: ContextUpdateCallback[] = [];
  private tokenHistory: Array<{ timestamp: Date; total: number }> = [];
  private readonly maxHistory = 100;
  private modelRegistry: ModelRegistry | null = null;
  private activeConversationId: string | undefined;
  /** Workspace URIs to match against trajectories */
  private workspaceUris: string[] = [];

  onUpdate(cb: ContextUpdateCallback): void {
    this.updateCallbacks.push(cb);
  }

  setModelRegistry(registry: ModelRegistry): void {
    this.modelRegistry = registry;
  }

  setWorkspaceUris(uris: string[]): void {
    this.workspaceUris = uris;
  }

  getLastSnapshot(): ContextSnapshot | null {
    return this.lastSnapshot;
  }

  getTokenHistory(): Array<{ timestamp: Date; total: number }> {
    return [...this.tokenHistory];
  }

  /**
   * Fetch real context data from trajectory steps.
   */
  async fetchContext(connection: ServerConnection): Promise<ContextSnapshot | null> {
    try {
      // 1. Get all trajectories to find the active conversation
      const trajectories = await this.rpcCall(
        connection,
        GET_TRAJECTORIES_PATH,
        {},
        (data) => (data.trajectorySummaries as Record<string, TrajectorySummary>) || null,
      );
      if (!trajectories) return null;

      // 2. Find the active trajectory (current workspace or most recent)
      const { id: cascadeId, traj: activeTraj } = this.findActiveTrajectory(trajectories);
      if (!cascadeId || !activeTraj) return null;

      this.activeConversationId = cascadeId;
      const stepCount = Number(activeTraj.stepCount || 0);
      const shortId = cascadeId.substring(0, 8);

      // 3. Fetch the last few steps to find the latest RESPONSE with token data
      let tokenInfo: StepTokenInfo | null = null;
      if (stepCount > 0) {
        // Fetch last 30 steps. Over-request endIndex because stepCount in
        // the trajectory summary may be stale (not updated during streaming).
        const startIdx = Math.max(0, stepCount - 30);
        const endIdx = stepCount + 50; // ask for more than stepCount to catch new steps
        logDebug(`Fetching steps ${startIdx}–${endIdx} for trajectory ${shortId}… (summary stepCount=${stepCount})`);
        tokenInfo = await this.fetchLatestTokenInfo(connection, cascadeId, startIdx, endIdx);
      }

      // 4. Build snapshot
      const snapshot = this.buildSnapshot(cascadeId, activeTraj, tokenInfo);
      this.lastSnapshot = snapshot;

      // Track history
      if (snapshot.totalTokens > 0) {
        this.tokenHistory.push({ timestamp: snapshot.timestamp, total: snapshot.totalTokens });
        if (this.tokenHistory.length > this.maxHistory) {
          this.tokenHistory.shift();
        }
      }

      for (const cb of this.updateCallbacks) {
        try { cb(snapshot); } catch { /* swallow */ }
      }

      return snapshot;
    } catch (err) {
      logWarning(`Context fetch error: ${err instanceof Error ? err.message : String(err)}`);
      return null;
    }
  }

  /**
   * Find the active trajectory matching the CURRENT workspace only.
   * Returns empty if no trajectory matches — we don't show stale data from other projects.
   */
  private findActiveTrajectory(
    trajectories: Record<string, TrajectorySummary>,
  ): { id?: string; traj?: TrajectorySummary } {
    let workspaceMatchId: string | undefined;
    let workspaceMatchTraj: TrajectorySummary | undefined;
    let workspaceMatchTime = 0;
    let matchCount = 0;

    for (const [id, traj] of Object.entries(trajectories)) {
      const modified = new Date(traj.lastModifiedTime || 0).getTime();

      // Only consider trajectories that match this workspace
      if (this.workspaceUris.length > 0 && traj.workspaces) {
        for (const ws of traj.workspaces) {
          const uri = ws.workspaceFolderAbsoluteUri || '';
          if (this.workspaceUris.some((u) => uri.includes(u) || u.includes(uri))) {
            matchCount++;
            if (modified > workspaceMatchTime) {
              workspaceMatchId = id;
              workspaceMatchTraj = traj;
              workspaceMatchTime = modified;
            }
          }
        }
      }
    }

    if (workspaceMatchId && workspaceMatchTraj) {
      const shortId = workspaceMatchId.substring(0, 8);
      const steps = workspaceMatchTraj.stepCount || 0;
      const status = workspaceMatchTraj.status || 'unknown';
      if (matchCount > 1) {
        logDebug(`Trajectory: ${shortId}… (${matchCount} matched, steps=${steps}, status=${status})`);
      }
      return { id: workspaceMatchId, traj: workspaceMatchTraj };
    }

    // No workspace match — don't fallback to another project
    logDebug(`No trajectory found for current workspace (${Object.keys(trajectories).length} total, ${this.workspaceUris.join(', ')})`);
    return {};
  }

  /**
   * Fetch the latest RESPONSE step's token data from trajectory steps.
   */
  private async fetchLatestTokenInfo(
    connection: ServerConnection,
    cascadeId: string,
    startIndex: number,
    endIndex: number,
  ): Promise<StepTokenInfo | null> {
    const data = await this.rpcCall<{ steps?: Array<Record<string, unknown>> }>(
      connection,
      GET_STEPS_PATH,
      { cascadeId, startIndex, endIndex },
      (d) => d,
    );
    if (!data?.steps) return null;

    logDebug(`Got ${data.steps.length} steps (requested ${startIndex}–${endIndex})`);

    // Diagnostic: show last 5 steps' types
    const lastN = Math.min(5, data.steps.length);
    const typeSummary: string[] = [];
    for (let j = data.steps.length - lastN; j < data.steps.length; j++) {
      const s = data.steps[j];
      typeSummary.push(`${startIndex + j}:${String(s.type || '?')}`);
    }
    logDebug(`Last ${lastN} steps: ${typeSummary.join(', ')}`);

    // Walk backwards to find the latest RESPONSE step with token data
    let dumpedMismatch = false;
    for (let i = data.steps.length - 1; i >= 0; i--) {
      const step = data.steps[i];
      const type = String(step.type || '');
      if (!type.includes('RESPONSE')) continue;

      // Search the step for token data — each field matched independently
      // because field order varies between API versions.
      // Support both quoted ("123") and unquoted (123) numeric values.
      const raw = JSON.stringify(step);
      const inputMatch = raw.match(/"inputTokens"\s*:\s*"?(\d+)"?/);
      const outputMatch = raw.match(/"outputTokens"\s*:\s*"?(\d+)"?/);
      if (!inputMatch || !outputMatch) {
        // Dump the FIRST non-matching RESPONSE step to diagnose format
        if (!dumpedMismatch) {
          dumpedMismatch = true;
          const snippet = raw.length > 500 ? raw.substring(0, 500) + '…' : raw;
          logDebug(`RESPONSE step ${startIndex + i} has no token data: ${snippet}`);
        }
        continue;
      }

      const inputTokens = parseInt(inputMatch[1], 10);
      const outputTokens = parseInt(outputMatch[1], 10);

      const cacheMatch = raw.match(/"cacheReadTokens"\s*:\s*"?(\d+)"?/);
      const cacheReadTokens = cacheMatch ? parseInt(cacheMatch[1], 10) : 0;

      const modelMatch = raw.match(/"model"\s*:\s*"([^"]+)"/);
      const model = modelMatch ? modelMatch[1] : 'Unknown';

      const providerMatch = raw.match(/"apiProvider"\s*:\s*"([^"]+)"/);
      const apiProvider = providerMatch ? providerMatch[1] : '';

      logDebug(
        `Step ${startIndex + i}/${data.steps.length}: ` +
        `input=${inputTokens} + cache=${cacheReadTokens} + out=${outputTokens}, ` +
        `model=${model}`,
      );

      return { model, inputTokens, outputTokens, cacheReadTokens, apiProvider };
    }

    return null;
  }

  private buildSnapshot(
    conversationId: string,
    traj: TrajectorySummary,
    tokenInfo: StepTokenInfo | null,
  ): ContextSnapshot {
    // Determine model name and context limit
    let modelName = 'Unknown';
    let contextLimit = 200_000;

    if (tokenInfo) {
      // Use API provider for display name
      modelName = API_PROVIDER_LABELS[tokenInfo.apiProvider] || tokenInfo.model;

      // Look up context limit from model registry
      if (this.modelRegistry) {
        const chatModels = this.modelRegistry.getChatModels();
        // Match by provider type
        const providerLC = tokenInfo.apiProvider.toLowerCase();
        let matchedModel = chatModels.find((m) => {
          const nameLC = m.displayName.toLowerCase();
          if (providerLC.includes('anthropic') && nameLC.includes('claude')) return true;
          if (providerLC.includes('google') && nameLC.includes('gemini')) return true;
          if (providerLC.includes('openai') && nameLC.includes('gpt')) return true;
          return false;
        });

        // Fallback: use highest context model matching the provider
        if (!matchedModel) {
          matchedModel = chatModels
            .filter((m) => m.maxTokens > 50_000)
            .sort((a, b) => b.maxTokens - a.maxTokens)[0];
        }

        if (matchedModel) {
          modelName = matchedModel.displayName;
          contextLimit = matchedModel.maxTokens;
        }
      }
    }

    // Token data
    const isEstimated = !tokenInfo;
    const rawInput = tokenInfo ? tokenInfo.inputTokens : 0;
    const cacheRead = tokenInfo ? tokenInfo.cacheReadTokens : 0;
    const inputTokens = rawInput + cacheRead;
    const outputTokens = tokenInfo ? tokenInfo.outputTokens : 0;
    const totalTokens = inputTokens + outputTokens;
    const usedPct = contextLimit > 0 ? (totalTokens / contextLimit) * 100 : 0;

    const status = traj.status || '';
    const isRunning = status.includes('RUNNING');

    if (tokenInfo) {
      logInfo(
        `Context: ${modelName} — ${totalTokens.toLocaleString()}/${contextLimit.toLocaleString()} ` +
        `(${usedPct.toFixed(1)}%) [input=${tokenInfo.inputTokens.toLocaleString()} + cache=${tokenInfo.cacheReadTokens.toLocaleString()} + out=${tokenInfo.outputTokens.toLocaleString()}]` +
        (isRunning ? ' 🔴 RUNNING' : ''),
      );
    }

    return {
      conversationId,
      model: modelName,
      inputTokens,
      cacheReadTokens: cacheRead,
      outputTokens,
      totalTokens,
      contextLimit,
      usedPercentage: Math.min(usedPct, 100),
      remainingTokens: Math.max(contextLimit - totalTokens, 0),
      isEstimated,
      timestamp: new Date(),
    };
  }

  /**
   * Generic RPC call helper.
   */
  private rpcCall<T>(
    connection: ServerConnection,
    path: string,
    payload: Record<string, unknown>,
    extract: (data: Record<string, unknown>) => T | null,
  ): Promise<T | null> {
    return new Promise((resolve) => {
      const body = JSON.stringify(payload);
      const req = http.request(
        {
          hostname: connection.host,
          port: connection.port,
          path,
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-Codeium-Csrf-Token': connection.csrfToken,
            'Content-Length': Buffer.byteLength(body),
          },
          timeout: 8000,
        },
        (res) => {
          let data = '';
          res.on('data', (chunk: Buffer) => { data += chunk.toString(); });
          res.on('end', () => {
            try {
              const parsed = JSON.parse(data);
              if (parsed.code && parsed.message) {
                // RPC error
                logDebug(`RPC error on ${path}: ${parsed.message}`);
                resolve(null);
                return;
              }
              resolve(extract(parsed));
            } catch {
              resolve(null);
            }
          });
        },
      );

      req.on('error', () => resolve(null));
      req.on('timeout', () => { req.destroy(); resolve(null); });
      req.write(body);
      req.end();
    });
  }
}
